# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%env(DB_HOST)%"
        port:     "%env(DB_PORT)%"
        dbname:   "%env(DB_NAME)%"
        user:     "%env(DB_USER)%"
        password: "%env(DB_PASSWORD)%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true